name: WorkFlow

on:
  push:
    branches: [ "feature/*" ]
  pull_request:
    branches: [ "feature/*" ]

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
  
  SonarCloud:
    runs-on: ubuntu-latest
    needs: Build
    steps:
      - name: Run SonarQube Analysis
        uses: ./.github/workflows/sonar.yaml
        with:
          args: 'sonar-scanner'
        env:
          GITHUB_TOKEN: ${{ secrets.SONAR_TOKEN }}

  Pull-Request:
    runs-on: ubuntu-latest
    needs: SonarCloud
    steps:
    - name: Buscando nome da branch
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      id: extract_branch

    - name: create pull request
      run: gh pr create -B main -H ${{ steps.extract_branch.outputs.branch }} --title 'Pull Request - ${{ steps.extract_branch.outputs.branch }} para main' --body 'Created by Github action'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

